version: '2'
services:
  apache:
    image: 'httpd:alpine'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - './config/apache/apache.conf:/usr/local/apache2/conf/httpd.conf'
    depends_on:
      - 'backend'

  backend:
    build:
      context: './config/backend'
      dockerfile: 'Dockerfile'
    ports:
      - '18080:8080'
      - '18000:8000'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - './src/SPRNGDKCR001:/usr/src/project'
      - 'm2_volume:/home/maven/.m2'
    depends_on:
      - 'db'
      
  db:
    build:
      context: './config/db'
      dockerfile: 'Dockerfile'
    ports:
      - '13306:3306'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
    environment:
      MYSQL_ROOT_PASSWORD: root123
      
volumes:
  m2_volume:
